# wrangler.toml (wrangler v3.88.0^)
name = "legal-forensics-api-dev-vish"
main = "cloudflare-worker.js"
compatibility_date = "2024-01-15"

# Enable logging for debugging
[observability.logs]
enabled = true

# Environment variables
# HUNTER_API_KEY should be set via Cloudflare Workers secrets
# Run: wrangler secret put HUNTER_API_KEY

# KV namespace for user data
[[kv_namespaces]]
binding = "LF_USERS_DATA"
id = "e8e677957ef7465daa8101b6c33a3378"
